
package com.corundumstudio.socketio.milkyway.soap;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.8
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "Directory", targetNamespace = "http://tempuri.org/", wsdlLocation = "http://192.168.0.29:7001/Directory.asmx?wsdl")
public class Directory
    extends Service
{

    private final static URL DIRECTORY_WSDL_LOCATION;
    private final static WebServiceException DIRECTORY_EXCEPTION;
    private final static QName DIRECTORY_QNAME = new QName("http://tempuri.org/", "Directory");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://192.168.0.29:7001/Directory.asmx?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        DIRECTORY_WSDL_LOCATION = url;
        DIRECTORY_EXCEPTION = e;
    }

    public Directory() {
        super(__getWsdlLocation(), DIRECTORY_QNAME);
    }

    public Directory(WebServiceFeature... features) {
        super(__getWsdlLocation(), DIRECTORY_QNAME, features);
    }

    public Directory(URL wsdlLocation) {
        super(wsdlLocation, DIRECTORY_QNAME);
    }

    public Directory(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, DIRECTORY_QNAME, features);
    }

    public Directory(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public Directory(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns DirectorySoap
     */
    @WebEndpoint(name = "DirectorySoap")
    public DirectorySoap getDirectorySoap() {
        return super.getPort(new QName("http://tempuri.org/", "DirectorySoap"), DirectorySoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns DirectorySoap
     */
    @WebEndpoint(name = "DirectorySoap")
    public DirectorySoap getDirectorySoap(WebServiceFeature... features) {
        return super.getPort(new QName("http://tempuri.org/", "DirectorySoap"), DirectorySoap.class, features);
    }

    /**
     * 
     * @return
     *     returns DirectorySoap
     */
    @WebEndpoint(name = "DirectorySoap12")
    public DirectorySoap getDirectorySoap12() {
        return super.getPort(new QName("http://tempuri.org/", "DirectorySoap12"), DirectorySoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns DirectorySoap
     */
    @WebEndpoint(name = "DirectorySoap12")
    public DirectorySoap getDirectorySoap12(WebServiceFeature... features) {
        return super.getPort(new QName("http://tempuri.org/", "DirectorySoap12"), DirectorySoap.class, features);
    }

    private static URL __getWsdlLocation() {
        if (DIRECTORY_EXCEPTION!= null) {
            throw DIRECTORY_EXCEPTION;
        }
        return DIRECTORY_WSDL_LOCATION;
    }

}
