
package com.corundumstudio.socketio.milkyway.soap;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.8
 * Generated source version: 2.2
 * 
 */
@WebService(name = "DirectorySoap", targetNamespace = "http://tempuri.org/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface DirectorySoap {


    /**
     *
     * @param id
     * @param securityKey
     * @return
     *     returns com.corundumstudio.socketio.milkyway.soap.ArrayOfFileModel
     */
    @WebMethod(operationName = "FileGet", action = "http://tempuri.org/FileGet")
    @WebResult(name = "FileGetResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "FileGet", targetNamespace = "http://tempuri.org/", className = "com.corundumstudio.socketio.milkyway.soap.FileGet")
    @ResponseWrapper(localName = "FileGetResponse", targetNamespace = "http://tempuri.org/", className = "com.corundumstudio.socketio.milkyway.soap.FileGetResponse")
    public ArrayOfFileModel fileGet(
        @WebParam(name = "securityKey", targetNamespace = "http://tempuri.org/")
        String securityKey,
        @WebParam(name = "id", targetNamespace = "http://tempuri.org/")
        int id);

    /**
     *
     * @param id
     * @param securityKey
     * @return
     *     returns com.corundumstudio.socketio.milkyway.soap.ArrayOfFileModel
     */
    @WebMethod(operationName = "GetCompressedImage", action = "http://tempuri.org/GetCompressedImage")
    @WebResult(name = "GetCompressedImageResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetCompressedImage", targetNamespace = "http://tempuri.org/", className = "com.corundumstudio.socketio.milkyway.soap.GetCompressedImage")
    @ResponseWrapper(localName = "GetCompressedImageResponse", targetNamespace = "http://tempuri.org/", className = "com.corundumstudio.socketio.milkyway.soap.GetCompressedImageResponse")
    public ArrayOfFileModel getCompressedImage(
        @WebParam(name = "securityKey", targetNamespace = "http://tempuri.org/")
        String securityKey,
        @WebParam(name = "id", targetNamespace = "http://tempuri.org/")
        int id);

    /**
     *
     * @param securityKey
     * @param objectID
     * @return
     *     returns com.corundumstudio.socketio.milkyway.soap.ArrayOfDirectoryItem
     */
    @WebMethod(operationName = "ObjectsChildGet", action = "http://tempuri.org/ObjectsChildGet")
    @WebResult(name = "ObjectsChildGetResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "ObjectsChildGet", targetNamespace = "http://tempuri.org/", className = "com.corundumstudio.socketio.milkyway.soap.ObjectsChildGet")
    @ResponseWrapper(localName = "ObjectsChildGetResponse", targetNamespace = "http://tempuri.org/", className = "com.corundumstudio.socketio.milkyway.soap.ObjectsChildGetResponse")
    public ArrayOfDirectoryItem objectsChildGet(
        @WebParam(name = "securityKey", targetNamespace = "http://tempuri.org/")
        String securityKey,
        @WebParam(name = "objectID", targetNamespace = "http://tempuri.org/")
        int objectID);

    /**
     *
     * @param securityKey
     * @param objectID
     * @return
     *     returns com.corundumstudio.socketio.milkyway.soap.ArrayOfDirectoryItem
     */
    @WebMethod(operationName = "SectionsGet", action = "http://tempuri.org/SectionsGet")
    @WebResult(name = "SectionsGetResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "SectionsGet", targetNamespace = "http://tempuri.org/", className = "com.corundumstudio.socketio.milkyway.soap.SectionsGet")
    @ResponseWrapper(localName = "SectionsGetResponse", targetNamespace = "http://tempuri.org/", className = "com.corundumstudio.socketio.milkyway.soap.SectionsGetResponse")
    public ArrayOfDirectoryItem sectionsGet(
        @WebParam(name = "securityKey", targetNamespace = "http://tempuri.org/")
        String securityKey,
        @WebParam(name = "objectID", targetNamespace = "http://tempuri.org/")
        int objectID);

    /**
     *
     * @param sectionID
     * @param securityKey
     * @param objectID
     * @return
     *     returns com.corundumstudio.socketio.milkyway.soap.ArrayOfFlat
     */
    @WebMethod(operationName = "FlatsGrammGet", action = "http://tempuri.org/FlatsGrammGet")
    @WebResult(name = "FlatsGrammGetResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "FlatsGrammGet", targetNamespace = "http://tempuri.org/", className = "com.corundumstudio.socketio.milkyway.soap.FlatsGrammGet")
    @ResponseWrapper(localName = "FlatsGrammGetResponse", targetNamespace = "http://tempuri.org/", className = "com.corundumstudio.socketio.milkyway.soap.FlatsGrammGetResponse")
    public ArrayOfFlat flatsGrammGet(
        @WebParam(name = "securityKey", targetNamespace = "http://tempuri.org/")
        String securityKey,
        @WebParam(name = "objectID", targetNamespace = "http://tempuri.org/")
        int objectID,
        @WebParam(name = "sectionID", targetNamespace = "http://tempuri.org/")
        int sectionID);

    /**
     *
     * @param rowPerPage
     * @param securityKey
     * @param sql
     * @param page
     * @param fields
     * @return
     *     returns com.corundumstudio.socketio.milkyway.soap.ArrayOfDI
     */
    @WebMethod(operationName = "Exec", action = "http://tempuri.org/Exec")
    @WebResult(name = "ExecResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "Exec", targetNamespace = "http://tempuri.org/", className = "com.corundumstudio.socketio.milkyway.soap.Exec")
    @ResponseWrapper(localName = "ExecResponse", targetNamespace = "http://tempuri.org/", className = "com.corundumstudio.socketio.milkyway.soap.ExecResponse")
    public ArrayOfDI exec(
        @WebParam(name = "securityKey", targetNamespace = "http://tempuri.org/")
        String securityKey,
        @WebParam(name = "sql", targetNamespace = "http://tempuri.org/")
        String sql,
        @WebParam(name = "fields", targetNamespace = "http://tempuri.org/")
        String fields,
        @WebParam(name = "rowPerPage", targetNamespace = "http://tempuri.org/")
        int rowPerPage,
        @WebParam(name = "page", targetNamespace = "http://tempuri.org/")
        int page);

    /**
     *
     * @param rowPerPage
     * @param userID
     * @param securityKey
     * @param sql
     * @param page
     * @param resultType
     * @param fields
     * @return
     *     returns com.corundumstudio.socketio.milkyway.soap.ArrayOfString
     */
    @WebMethod(operationName = "Exec2", action = "http://tempuri.org/Exec2")
    @WebResult(name = "Exec2Result", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "Exec2", targetNamespace = "http://tempuri.org/", className = "com.corundumstudio.socketio.milkyway.soap.Exec2")
    @ResponseWrapper(localName = "Exec2Response", targetNamespace = "http://tempuri.org/", className = "com.corundumstudio.socketio.milkyway.soap.Exec2Response")
    public ArrayOfString exec2(
        @WebParam(name = "securityKey", targetNamespace = "http://tempuri.org/")
        String securityKey,
        @WebParam(name = "sql", targetNamespace = "http://tempuri.org/")
        String sql,
        @WebParam(name = "userID", targetNamespace = "http://tempuri.org/")
        String userID,
        @WebParam(name = "fields", targetNamespace = "http://tempuri.org/")
        String fields,
        @WebParam(name = "rowPerPage", targetNamespace = "http://tempuri.org/")
        String rowPerPage,
        @WebParam(name = "page", targetNamespace = "http://tempuri.org/")
        String page,
        @WebParam(name = "resultType", targetNamespace = "http://tempuri.org/")
        String resultType);

    /**
     *
     * @param rowPerPage
     * @param userID
     * @param securityKey
     * @param sql
     * @param page
     * @param resultType
     * @param fields
     * @return
     *     returns com.corundumstudio.socketio.milkyway.soap.ArrayOfString
     */
    @WebMethod(operationName = "Exec2_Immutable", action = "http://tempuri.org/Exec2_Immutable")
    @WebResult(name = "Exec2_ImmutableResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "Exec2_Immutable", targetNamespace = "http://tempuri.org/", className = "com.corundumstudio.socketio.milkyway.soap.Exec2Immutable")
    @ResponseWrapper(localName = "Exec2_ImmutableResponse", targetNamespace = "http://tempuri.org/", className = "com.corundumstudio.socketio.milkyway.soap.Exec2ImmutableResponse")
    public ArrayOfString exec2Immutable(
        @WebParam(name = "securityKey", targetNamespace = "http://tempuri.org/")
        String securityKey,
        @WebParam(name = "sql", targetNamespace = "http://tempuri.org/")
        String sql,
        @WebParam(name = "userID", targetNamespace = "http://tempuri.org/")
        String userID,
        @WebParam(name = "fields", targetNamespace = "http://tempuri.org/")
        String fields,
        @WebParam(name = "rowPerPage", targetNamespace = "http://tempuri.org/")
        String rowPerPage,
        @WebParam(name = "page", targetNamespace = "http://tempuri.org/")
        String page,
        @WebParam(name = "resultType", targetNamespace = "http://tempuri.org/")
        String resultType);

    /**
     *
     * @param securityKey
     * @param phoneID
     * @return
     *     returns int
     */
    @WebMethod(operationName = "UserIdByPhoneIDGet", action = "http://tempuri.org/UserIdByPhoneIDGet")
    @WebResult(name = "UserIdByPhoneIDGetResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "UserIdByPhoneIDGet", targetNamespace = "http://tempuri.org/", className = "com.corundumstudio.socketio.milkyway.soap.UserIdByPhoneIDGet")
    @ResponseWrapper(localName = "UserIdByPhoneIDGetResponse", targetNamespace = "http://tempuri.org/", className = "com.corundumstudio.socketio.milkyway.soap.UserIdByPhoneIDGetResponse")
    public int userIdByPhoneIDGet(
        @WebParam(name = "securityKey", targetNamespace = "http://tempuri.org/")
        String securityKey,
        @WebParam(name = "phoneID", targetNamespace = "http://tempuri.org/")
        String phoneID);

    /**
     *
     * @param userID
     * @param securityKey
     * @param sql
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "ExecScalar", action = "http://tempuri.org/ExecScalar")
    @WebResult(name = "ExecScalarResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "ExecScalar", targetNamespace = "http://tempuri.org/", className = "com.corundumstudio.socketio.milkyway.soap.ExecScalar")
    @ResponseWrapper(localName = "ExecScalarResponse", targetNamespace = "http://tempuri.org/", className = "com.corundumstudio.socketio.milkyway.soap.ExecScalarResponse")
    public String execScalar(
        @WebParam(name = "securityKey", targetNamespace = "http://tempuri.org/")
        String securityKey,
        @WebParam(name = "sql", targetNamespace = "http://tempuri.org/")
        String sql,
        @WebParam(name = "userID", targetNamespace = "http://tempuri.org/")
        String userID);

    /**
     *
     * @param securityKey
     * @param sqlList
     * @return
     *     returns boolean
     */
    @WebMethod(operationName = "ExecMultiply", action = "http://tempuri.org/ExecMultiply")
    @WebResult(name = "ExecMultiplyResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "ExecMultiply", targetNamespace = "http://tempuri.org/", className = "com.corundumstudio.socketio.milkyway.soap.ExecMultiply")
    @ResponseWrapper(localName = "ExecMultiplyResponse", targetNamespace = "http://tempuri.org/", className = "com.corundumstudio.socketio.milkyway.soap.ExecMultiplyResponse")
    public boolean execMultiply(
        @WebParam(name = "securityKey", targetNamespace = "http://tempuri.org/")
        String securityKey,
        @WebParam(name = "sqlList", targetNamespace = "http://tempuri.org/")
        ArrayOfString sqlList);

    /**
     *
     * @param securityKey
     * @param sql
     * @param fileData
     * @return
     *     returns com.corundumstudio.socketio.milkyway.soap.ArrayOfString
     */
    @WebMethod(operationName = "AttachmentIns", action = "http://tempuri.org/AttachmentIns")
    @WebResult(name = "AttachmentInsResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "AttachmentIns", targetNamespace = "http://tempuri.org/", className = "com.corundumstudio.socketio.milkyway.soap.AttachmentIns")
    @ResponseWrapper(localName = "AttachmentInsResponse", targetNamespace = "http://tempuri.org/", className = "com.corundumstudio.socketio.milkyway.soap.AttachmentInsResponse")
    public ArrayOfString attachmentIns(
        @WebParam(name = "securityKey", targetNamespace = "http://tempuri.org/")
        String securityKey,
        @WebParam(name = "sql", targetNamespace = "http://tempuri.org/")
        String sql,
        @WebParam(name = "fileData", targetNamespace = "http://tempuri.org/")
        byte[] fileData);

}
